name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check dependencies
      run: |
        go mod verify

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: -D errcheck

    - name: Run test
      run: |
        go test -v ./...

